name: settings_ui
description: Create native settings for Flutter app in minutes. Use single interfaces to build
version: 2.0.3
homepage: https://github.com/yako-dev/flutter-settings-ui

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
